import { describe, it, expect } from 'vitest';
import {
  generateServerTs,
  generatePackageJson,
  generateTsConfig,
} from '../../src/generator/server-template.js';
import type { NormalizedSpec, AuthScheme } from '../../src/types.js';

const minimalSpec: NormalizedSpec = {
  info: { title: 'My API', version: '2.1.0' },
  servers: [{ url: 'https://api.example.com' }],
  endpoints: [],
  auth: [],
  rawFormat: 'openapi3',
};

const bearerScheme: AuthScheme = {
  name: 'bearerAuth',
  type: 'http',
  scheme: 'bearer',
  envVar: 'MYAPI_BEARER',
};

const apiKeyScheme: AuthScheme = {
  name: 'apiKey',
  type: 'apiKey',
  in: 'header',
  envVar: 'MYAPI_APIKEY',
};

describe('generateServerTs — structure', () => {
  it('includes mcpify attribution comment', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Generated by mcpify');
  });

  it('includes API title and version in McpServer config', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('my-api');
    expect(src).toContain('2.1.0');
  });

  it('uses node:sqlite import', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("from 'node:sqlite'");
  });

  it('ends with server.connect', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('server.connect(transport)');
  });
});

describe('generateServerTs — 2-tool architecture', () => {
  it('registers {slug}_search_docs tool using slug variable', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain("const _slug = 'my-api'");
    expect(src).toContain('`${_slug}_search_docs`');
  });

  it('registers {slug}_call_api tool using slug variable', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('`${_slug}_call_api`');
  });

  it('does NOT register per-endpoint tools', () => {
    const specWithEndpoints: NormalizedSpec = {
      ...minimalSpec,
      endpoints: [
        { id: 'listPets', method: 'GET', path: '/pets', tags: [], parameters: [], responses: [] },
        { id: 'createPet', method: 'POST', path: '/pets', tags: [], parameters: [], responses: [] },
      ],
    };
    const src = generateServerTs(specWithEndpoints, [], 'openai', 'text-embedding-3-small');
    // Should not have tool registrations for individual endpoints
    expect(src).not.toContain("'listPets'");
    expect(src).not.toContain("'createPet'");
    // Should still only have exactly 2 server.tool( calls
    const toolCount = (src.match(/server\.tool\(/g) ?? []).length;
    expect(toolCount).toBe(2);
  });

  it('call_api looks up endpoint from SQLite by ID', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('SELECT endpoint_json FROM endpoints WHERE id = ?');
    expect(src).toContain('endpoint_id');
  });

  it('call_api returns helpful error when endpoint ID is unknown', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Unknown endpoint');
    expect(src).toContain('Available IDs');
  });

  it('call_api accepts params and body inputs', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('params:');
    expect(src).toContain('body:');
  });

  it('call_api substitutes path params into URL', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('path.replace');
    expect(src).toContain('encodeURIComponent');
  });

  it('search_api_docs uses cosine similarity for ranking', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('_cosineSimilarity');
    expect(src).toContain('.sort((a, b) => b.score - a.score)');
  });

  it('search results include endpoint ID for use in call_api', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('ep.id');
  });
});

describe('generateServerTs — auth', () => {
  it('adds startup warning for each missing env var', () => {
    const src = generateServerTs(minimalSpec, [bearerScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('MYAPI_BEARER');
    expect(src).toContain('console.warn');
  });

  it('injects bearer Authorization header in call_api', () => {
    const src = generateServerTs(minimalSpec, [bearerScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('Authorization');
    expect(src).toContain('Bearer');
    expect(src).toContain('MYAPI_BEARER');
  });

  it('injects custom header for apiKey scheme', () => {
    const src = generateServerTs(minimalSpec, [apiKeyScheme], 'openai', 'text-embedding-3-small');
    expect(src).toContain('apiKey');
    expect(src).toContain('MYAPI_APIKEY');
  });

  it('skips auth section when no schemes', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('No authentication required');
  });
});

describe('generateServerTs — embedding providers', () => {
  it('uses OpenAI client when provider is openai', () => {
    const src = generateServerTs(minimalSpec, [], 'openai', 'text-embedding-3-small');
    expect(src).toContain('OpenAI');
    expect(src).toContain('text-embedding-3-small');
    expect(src).not.toContain('OLLAMA_HOST');
  });

  it('uses Ollama fetch when provider is ollama', () => {
    const src = generateServerTs(minimalSpec, [], 'ollama', 'nomic-embed-text');
    expect(src).toContain('OLLAMA_HOST');
    expect(src).toContain('nomic-embed-text');
    expect(src).not.toContain('new OpenAI');
  });

  it('uses @huggingface/transformers pipeline when provider is local', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain('@huggingface/transformers');
    expect(src).toContain('feature-extraction');
    expect(src).toContain('Qwen3-Embedding-0.6B-ONNX');
  });

  it('applies query instruct prefix for local provider', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain('Instruct:');
    expect(src).toContain('Query:');
  });

  it('caches local pipeline at module level', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain('_localPipeline');
    // should declare it before server.tool, not inside the function
    const pipelineDecl = src.indexOf('let _localPipeline');
    const serverToolDecl = src.indexOf('server.tool(');
    expect(pipelineDecl).toBeLessThan(serverToolDecl);
  });

  it('uses last_token pooling and normalize for local provider', () => {
    const src = generateServerTs(minimalSpec, [], 'local', 'onnx-community/Qwen3-Embedding-0.6B-ONNX');
    expect(src).toContain("pooling: 'last_token'");
    expect(src).toContain('normalize: true');
  });
});

describe('generatePackageJson', () => {
  it('includes openai dep when provider is openai', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).toHaveProperty('openai');
  });

  it('excludes openai when provider is ollama', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'ollama'));
    expect(pkg.dependencies).not.toHaveProperty('openai');
  });

  it('always includes @modelcontextprotocol/sdk and zod', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).toHaveProperty('@modelcontextprotocol/sdk');
    expect(pkg.dependencies).toHaveProperty('zod');
  });

  it('sanitizes package name', () => {
    const pkg = JSON.parse(generatePackageJson('My Cool API!', '1.0.0', 'openai'));
    expect(pkg.name).toBe('my-cool-api-mcp');
  });

  it('does NOT include better-sqlite3 or sqlite-vec', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'openai'));
    expect(pkg.dependencies).not.toHaveProperty('better-sqlite3');
    expect(pkg.dependencies).not.toHaveProperty('sqlite-vec');
  });

  it('includes @huggingface/transformers when provider is local', () => {
    const pkg = JSON.parse(generatePackageJson('My API', '1.0.0', 'local'));
    expect(pkg.dependencies).toHaveProperty('@huggingface/transformers');
    expect(pkg.dependencies).not.toHaveProperty('openai');
  });

  it('requires node >= 22.5.0', () => {
    const pkg = JSON.parse(generatePackageJson('API', '1.0.0', 'openai'));
    expect(pkg.engines.node).toContain('22');
  });
});

describe('generateTsConfig', () => {
  it('returns valid JSON', () => {
    expect(() => JSON.parse(generateTsConfig())).not.toThrow();
  });

  it('targets ES2022 with NodeNext modules', () => {
    const cfg = JSON.parse(generateTsConfig());
    expect(cfg.compilerOptions.target).toBe('ES2022');
    expect(cfg.compilerOptions.moduleResolution).toBe('NodeNext');
    expect(cfg.compilerOptions.strict).toBe(true);
  });
});
